config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "dsl_info#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/stats/all", to: "stats#all"
  get "/stats/male", to: "stats#male"
  get "/stats/female", to: "stats#female"
  get '/dsl_info/adjusted', to:'dsl_info#adjusted'

  resources :stats
  resources :players
  resources :seasons
  resources :eras
  resources :every
  resources :dsl_info
  resources :years
  resources :teams do
    collection do
      get 'all'
    end
    collection do
      get 'coach'
    end
  end
  get 'teams/all', to: 'teams#all', as: :teams_all
  get 'teams/coach', to: 'teams#coach', as: :teams_coach


  resources :charts 
  
  

  get "/comparison", to: "comparison#index"
  get "/about", to: "about#index"
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/dsl_info_controller.rb
class DslInfoController < ApplicationController
    def index
        if params[:gender_toggle] == "0"
            players = Player.where(gender: "f").joins(:stats)
            single_season_player = Stat.joins(:player).where(player: { gender: "f"})
        elsif params[:gender_toggle] == "1"
            players = Player.where(gender: "m").joins(:stats)
            single_season_player = Stat.joins(:player).where(player: { gender: "m"})
        else
           players = Player.where(gender: "m").joins(:stats)
           single_season_player = Stat.joins(:player).where(player: {gender: "m"})
        end
        # females = Player.where(gender: "f").joins(:stats)
        #females_single_season = Stat.joins(:player).where(player: { gender: "f" })

        def top_players_by_stat(players, stat)
            players
              .group(:id)
              .sort_by { |player| -player.stats.sum(stat) }
              .first(5)
          end
        
          @hits = top_players_by_stat(players, "hits")
          @games = top_players_by_stat(players, "games")
          @runs = top_players_by_stat(players, "runs")
          @homers = top_players_by_stat(players, "homeruns")
          @tb = top_players_by_stat(players, "tb")
          @doubles = top_players_by_stat(players, "doubles")
          @triples = top_players_by_stat(players, "triples")
        

        @avg = players.group(:id).having("stats.count > ?", 5).sort_by{|player| -average(player)}
        @avg = @avg.first(5)
        
        @singlehits = single_season_player.sort_by{|stat| -stat.hits}
        @singlehits = @singlehits.first(5)

        @singleruns = single_season_player.sort_by{|stat| -stat.runs}
        @singleruns = @singleruns.first(5)
        
        @singlerbi = single_season_player.sort_by{|stat| -stat.rbi}
        @singlerbi = @singlerbi.first(5)

        @singlehr = single_season_player.sort_by{|stat| -stat.homeruns}
        @singlehr = @singlehr.first(5)

        @singletb = single_season_player.sort_by{|stat| -stat.tb}
        @singletb = @singletb.first(5)

        @singledoubles = single_season_player.sort_by {|stat| -stat.doubles}.first(5)

        @singleavg = single_season_player.where("atbat >= ?", 25).sort_by { |stat| -stat.avg}.first(5)

        opsPlus_array = single_season_player.where("atbat >= ?", 25).map do |stat|
            [stat, stat.opsPlus]
        end

        sorted_opsPlus = opsPlus_array.sort_by { |pair| -pair[1] }  # Sort in descending order

        @singleopsPlus = sorted_opsPlus.first(5).map(&:first)  # Extracting only the player records

        slgPlus_array = single_season_player.where("atbat>= ?", 20).map do |stat|
            [stat, stat.slgPlus]
        end

        sorted_slgPlus = slgPlus_array.sort_by { |pair| -pair[1]}
        
        @singleslgPlus = sorted_slgPlus.first(5).map(&:first)

        #  respond_to do |format|
        #     format.turbo_stream { render turbo_stream: turbo_stream.replace("leaderboards", partial: "player_leaderboards", locals: { players: players }) }
        #     format.html {render 'index', locals: {players: players}}
        #   end
    end

    def adjusted
        single_season_player = Stat.joins(:player)

        opsPlus_array = single_season_player.where("atbat >= ?", 25).map do |stat|
            [stat, stat.opsPlus]
        end
        sorted_opsPlus = opsPlus_array.sort_by { |pair| -pair[1] }  # Sort in descending order
        @singleopsPlus = sorted_opsPlus.first(25).map(&:first)  # Extracting only the player records
        
        slgPlus_array = single_season_player.where("atbat>= ?", 20).map do |stat|
            [stat, stat.slgPlus]
        end
        sorted_slgPlus = slgPlus_array.sort_by { |pair| -pair[1]}
        @singleslgPlus = sorted_slgPlus.first(25).map(&:first)

    end

    def average(player)
        if player.stats.sum(:hits) == 0 || player.stats.sum(:atbat) == 0
            return 0.00
        else
        avg = (player.stats.sum(:hits).to_d / player.stats.sum(:atbat).to_d)
        avg.round(3)
        end
      end
end

app/views/dsl_info/_banner.html.erb
<div class="pb-6 flex flex-col md:flex-row">
<%# <div class="bg-gradient-to-t from-transparent via-gray-600 to-black absolute w-full h-1/2 md:py-4"> %>
<%= image_tag "dsl.jpg", class:"md:w-1/2"%>
<div class="flex flex-col justify-center  bg-[#50AE26] py-3">
<h1 class="text-2xl lg:text-8xl text-center text-white md:py-10 block font-bold p-0 m-0">Welcome to DSLGraphs</h1>
<p class="text-white text-center w-3/4 items-center mx-auto pt-3">A website dedicated to sharing DSL stats from the last <%=Season.count%> seasons.
</div>
</div>

app/views/dsl_info/_gender_toggle.html.erb
<div class="d-flex flex-row gap-3 font-light pb-1">
<div>Female</div>
<%= form_with url: dsl_info_index_path, class: "inline z-0", id: "gender_form", method: :get do |form| %>
  <label class="relative inline-flex items-center cursor-pointer">
    <%= form.check_box :gender_toggle, class: "sr-only peer z-0" %>
      <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-blue-300  rounded-full peer  peer-checked:after:translate-x-full peer-checked:after:border-[#50AE26] after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-[#50AE26] after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#50AE26] z-0" id="toggle"></div>
    </label>
<% end %>
<div>Male</div>
</div>

<script>
document.addEventListener('turbo:load', function() {
  const genderToggle = document.getElementById('gender_toggle');
  const genderForm = document.getElementById('gender_form')
  const storedGender = localStorage.getItem('selectedGender') || 'male';
 
  genderToggle.checked = storedGender === 'male';


  genderToggle.addEventListener('change', () => {
    const storedGender = genderToggle.checked ? 'male' : 'female';
    localStorage.setItem('selectedGender', storedGender);
    genderForm.submit();
  });
  });
</script>

app/views/dsl_info/_players_individual_leaderboards.erb
<table class ="w-80 bg-white tablesorter shadow rounded border-b border-gray-200">
        <thead class = "bg-[#50AE26] text-white">
        <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Rank</th>
        <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Name</th>
        <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer"><%=stat_label%></th>
        <thead>
        <tbody class = "text-gray-700">
        <%players.each_with_index do |player, index|%>
        <tr class = "hover:bg-gray-200">
        <td class = "text-left py-1 px-2"><%=index + 1%></td>
        <td class="text-left py-1 px-2"><%=link_to player.name, player_path(player)%></td>
        <td class="text-left py-1 px-2"><%=player.stats.sum(stat_column)%></td>
        </tr>
        <%end%>
        </tbody>
      </table>
      <div class = "w-80 shadow bg-white rounded border-t border-gray-200 text-gray-400
        text-center py-2"><%= link_to complete_stats_label, stats_all_path(sort: stat_column, order: "asc", query_seasons: "6") %>
      </div>
   
    

app/views/dsl_info/adjusted.html.erb
<div class = "flex flex-col items-center gap-4 pb-10">
  <div class="flex flex-col">
    <h1 class = "text-2xl md:text-6xl my-4 p-2 text-center bg-[#50AE26] text-white w-1/2 place-self-center" >Adjusted Stats</h1>
    <p class = "text-l md:text-xl text-center p-1 w-1/2 place-self-center">This page allows you to see the top 25 seasons for OPS+ and SLG+.
    OPS+ and SLG+ are adjusted stats, meaning they compare a players performance in one season against the rest of the leagues performance during that season.
    The effective difference here is that OPS+ includes batting average, while SLG+ removes batting average and focuses only on power.
    Only players with 20 or more atbats are eligible</h2>
    </div>
  <div class="flex flex-col md:flex-row gap-10 flex-1">
    <div class="h-full">
      <table class ="w-96 bg-white tablesorter shadow rounded border-b border-gray-200">
        <thead class = "bg-[#50AE26] text-white">
          <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Rank</th>
          <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Team</th>
          <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Name</th>
          <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Year</th>
          <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">OPS+</th>
        <thead>
        <tbody class = "text-gray-700">
          <%@singleopsPlus.each_with_index do |player, index|%>
            <tr class="hover:bg-gray-200">
              <td class="text-left py-1 px-2"><%=index + 1%></td>
              <td class="text-left py-1 px-2"><%=link_to player.player.name, player_path(player.player)%></td>
              <td class="text-left py-1 px-2"><%=player.team.team_name%></td>
              <td class="text-left py-1 px-2"><%=player.years%></td>
              <td class="text-left py-1 px-2"><%=number_with_precision(player.opsPlus, precision: 0)%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  <div class="h-full">
  <table class ="w-96 bg-white shadow rounded border-b border-gray-200">
    <thead class = "bg-[#50AE26] text-white">
    <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Rank</th>
    <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Name</th>
    <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Team</th>
    <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">Year</th>
    <th class = "text-left py-3 px-2 uppercase font-semibold text-sm hover:cursor-pointer">SLG+</th>
    <thead>
    <tbody class = "text-gray-700">
    <%@singleslgPlus.each_with_index do |player, index|%>
        <tr class="hover:bg-gray-200">
        <td class="text-left py-1 px-2"><%=index + 1%></td>
        <td class="text-left py-1 px-2"><%=link_to player.player.name, player_path(player.player)%></td>
        <td class="text-left py-1 px-2"><%=player.team.team_name%></td>
        <td class="text-left py-1 px-2"><%=player.years%></td>
        <td class="text-left py-1 px-2"><%=number_with_precision(player.slgPlus, precision: 0)%></td>
    </tr>
    <%end%>
    <tbody>
  </table>
</div>
</div>
</div>

app/views/dsl_info/index.html.erb
<div class = "flex flex-col justify-center items-center">
  <%=render "banner"%>
  <h1 class = "text-3xl text-center pb-3">Career Leaders</h1>
  <%=render "gender_toggle"%>
  <div class="grid grid-cols-1 md:grid-cols-3 gap-4 place-content-evenly">
    <%=render "players_leaderboards"%>
  </div>

  <a href="#gender_form" class="animate-bounce fixed bottom-4 right-4 w-10 h-10 border border-white bg-[#50AE26] rounded-full flex items-center justify-center text-white opacity-70">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18"></path>
    </svg>
  </a>

</div>