config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "dsl_info#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/stats/all", to: "stats#all"
  get "/stats/male", to: "stats#male"
  get "/stats/female", to: "stats#female"
  get '/dsl_info/adjusted', to:'dsl_info#adjusted'

  resources :stats
  resources :players
  resources :seasons
  resources :eras
  resources :every
  resources :dsl_info
  resources :years
  resources :teams do
    collection do
      get 'all'
    end
    collection do
      get 'coach'
    end
  end
  get 'teams/all', to: 'teams#all', as: :teams_all
  get 'teams/coach', to: 'teams#coach', as: :teams_coach


  resources :charts 
  
  

  get "/comparison", to: "comparison#index"
  get "/about", to: "about#index"
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<div class ="z-50 <%=controller_name === "dsl_info" ? "sticky top-0" : ""%>">
<div class = "w-100vw bg-[#50AE26] px-2 m:px-32 py-2 font-semibold"><%=link_to image_tag("fg.png", size: "50x50", class: "inline-block"), root_path%><span class = "pl-2"><%=link_to "DSL", root_path%></span><%=link_to "GRAPHS", root_path, class:"text-white pr-2"%></div>
  <div class = "w-100vw bg-black px-2 m:px-32 py-2 text-white font-semibold md:flex gap-3">
    <div class= "hidden md:flex md:gap-3">
      <%=link_to "Career", stats_all_path, class:"peer block hover:text-[#50AE26] active:text-blue px-2"%>
        <div class="hidden rounded peer-hover:block absolute hover:flex flex-col bg-black px-2 mt-6">
          <%=link_to "All", stats_all_path, class:"block px-2 py-2 text-white hover:bg-gray-800"%>
          <%=link_to "Male", stats_male_path, class:"block px-2 py-2 text-white hover:bg-gray-800"%>
          <%=link_to "Female", stats_female_path, class:"block px-2 py-2 text-white hover:bg-gray-800"%>
        </div>
      
      <%=link_to "Season", seasons_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "All", every_index_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "Eras", eras_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "LeaderBoards", root_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "Comparisons", comparison_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "Teams", teams_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <%=link_to "Years", years_path, class: "hover:text-[#50AE26] active:text-blue px-2"%>
      <div>
      <%=link_to "About", about_path, class: "hidden md:flex hover:text-[#50AE26] active:text-blue px-2"%>
      
  </div>
  </div>

   <div class="md:hidden flex items-center">
	  <button class="outline-none mobile-menu-button my-2">
		<svg
			class="w-6 h-6 text-white"
			x-show="!showMenu"
			fill="none"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="2"
			viewBox="0 0 24 24"
			stroke="currentColor"
		>
		<path d="M4 6h16M4 12h16M4 18h16"></path>
		</svg>
	</button>
</div>
  <div class="hidden transition mobile-menu absolute w-full bg-black left-0 p-4 rounded-b z-50">
	  <ul class="flex flex-col gap-3">
	    <%=link_to "Career", stats_all_path, class: "hover:text-[#50AE26] active:text-blue"%>
	    <%=link_to "Male Stats", stats_male_path, class: "hover:text-[#50AE26] active:text-blue pl-3"%>
	    <%=link_to "Female Stats", stats_female_path, class: "hover:text-[#50AE26] active:text-blue pl-3"%>
      <%=link_to "Season", seasons_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "All", every_index_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "Eras", eras_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "LeaderBoards", root_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "Comparisons", comparison_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "Teams", teams_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "Years", years_path, class: "hover:text-[#50AE26] active:text-blue"%>
      <%=link_to "About", about_path, class: "hover:text-[#50AE26] active:text-blue"%>
	</ul>
</div>
  </div>
  </div>

<script type="text/javascript">
	hamburgerMenu = () => {// Grab HTML Elements
	const menuBtn = document.querySelector("button.mobile-menu-button");
	const menu = document.querySelector(".mobile-menu");

	// Add Event Listeners

  const toggleMenu = () => {
    menu.classList.toggle("hidden")
  }
	menuBtn.addEventListener("click", () => {
	menu.classList.toggle("hidden");
	});
  menuBtn.removeEventListener("click", () => {
    menu.classList.toggle("hidden")
  })

  }

  hamburgerMenu()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DSL Stats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("fg.png")%>

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


  </head>

  <body>
  <%= render "layouts/navbar"%>
    <main class="<%=controller_name != "dsl_info" ? "container" : ""%>">
      

      <%= yield %>

      
    </main>
    </div>
    

  </body>
</html>